name: mine_sweeper
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Redux for general global state
  redux: ^3.0.0
  flutter_redux: ^0.5.3

  #For provider, for local component with more state  
  provider: ^3.1.0+1

  #For immutable data types (Prevents bugs, makes Redux easier)
  build_runner: ^1.7.2
  built_value: ^6.7.1
  built_value_generator: ^6.7.1

  #For Date formatting
  intl: ^0.16.0

  #For stricter static analysis
  pedantic: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true